// <auto-generated />
using System;
using FU_House_Finder.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FU_House_Finder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FU_House_Finder.Repositories.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PowerPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Km 29, Đại lộ Thăng Long, Hòa Lạc, Hà Nội",
                            CampusName = "Hòa Lạc",
                            CreatedDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nhà trọ sạch sẽ, an toàn, gần trường",
                            IsDeleted = false,
                            LandlordId = 1,
                            Name = "Nhà trọ Hòa Lạc A",
                            PowerPrice = 3500m,
                            WaterPrice = 2000m
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 Phố Cầu Giấy, Cầu Giấy, Hà Nội",
                            CampusName = "Cầu Giấy",
                            CreatedDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nhà trọ hiện đại, đủ tiện nghi",
                            IsDeleted = false,
                            LandlordId = 2,
                            Name = "Nhà trọ Cầu Giấy B",
                            PowerPrice = 4000m,
                            WaterPrice = 2500m
                        },
                        new
                        {
                            Id = 3,
                            Address = "456 Đường Thanh Xuân, Thanh Xuân, Hà Nội",
                            CampusName = "Thanh Xuân",
                            CreatedDate = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nhà trọ yên tĩnh, quanh quẩn tiện lợi",
                            IsDeleted = false,
                            LandlordId = 3,
                            Name = "Nhà trọ Thanh Xuân C",
                            PowerPrice = 3800m,
                            WaterPrice = 2200m
                        });
                });

            modelBuilder.Entity("FU_House_Finder.Repositories.Models.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("FU_House_Finder.Repositories.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Area")
                        .HasColumnType("real");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<int>("MaxPeople")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 25f,
                            Description = "Có điều hòa, nóng lạnh, WiFi",
                            HouseId = 1,
                            MaxPeople = 2,
                            Name = "P.101",
                            Price = 3000000m,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Area = 30f,
                            Description = "Có điều hòa, nóng lạnh, WiFi, tủ lạnh",
                            HouseId = 1,
                            MaxPeople = 3,
                            Name = "P.102",
                            Price = 3500000m,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Area = 20f,
                            Description = "Có điều hòa, WiFi",
                            HouseId = 1,
                            MaxPeople = 1,
                            Name = "P.103",
                            Price = 2800000m,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Area = 35f,
                            Description = "Phòng cao cấp, đầy đủ tiện nghi, có bàn làm việc",
                            HouseId = 2,
                            MaxPeople = 2,
                            Name = "P.201",
                            Price = 4000000m,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            Area = 32f,
                            Description = "Phòng rộng, có cửa sổ, điều hòa, nóng lạnh",
                            HouseId = 2,
                            MaxPeople = 2,
                            Name = "P.202",
                            Price = 3800000m,
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            Area = 28f,
                            Description = "Phòng thoáng mát, cách âm tốt, có WiFi",
                            HouseId = 3,
                            MaxPeople = 2,
                            Name = "P.301",
                            Price = 3200000m,
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
