// <auto-generated />
using FU_House_Finder_Auth.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FU_House_Finder_Auth.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211104734_initDb")]
    partial class initDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FU_House_Finder_Auth.Repositories.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@fuhouse.com",
                            FullName = "Admin User",
                            IsActive = true,
                            PasswordHash = "123",
                            PhoneNumber = "0123456789",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "staff@fuhouse.com",
                            FullName = "Staff User",
                            IsActive = true,
                            PasswordHash = "staff123",
                            PhoneNumber = "0123456790",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "landlord@fuhouse.com",
                            FullName = "Landlord User",
                            IsActive = true,
                            PasswordHash = "landlord123",
                            PhoneNumber = "0123456791",
                            Role = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "student@fuhouse.com",
                            FullName = "Student User",
                            IsActive = true,
                            PasswordHash = "student123",
                            PhoneNumber = "0123456792",
                            Role = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
